In [12]:
from sklearn.datasets import load_iris
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import cross_val_score
#from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
#from sklearn.tree import DecisionTreeClassifier
#from sklearn import tree
iris = load_iris()
#from IPython.display import  Image
#import graphviz
#import pydot
#from sklearn.externals.six import StringIO
#dot = StringIO()
clf = AdaBoostClassifier(n_estimators=10,algorithm="SAMME.R")
clf.fit(iris.data, iris.target)
score = cross_val_score(clf,iris.data,iris.target)                       
print(score.mean()) 

0.9669117647058822


In [14]:
from xgboost import XGBClassifier 

In [15]:
#Ensembler based on xgboost Gradient boosting.
    
#Loading data
#X, X_test, n_preds, n_class = get_X_X_Test(valid_folder, test_folder)
#y = y_valid
    
#Defining classifier
xgb = XGBClassifier(max_depth=4, learning_rate=0.05, n_estimators=200,
                        objective='multi:softprob', gamma=0., 
                        max_delta_step=0., subsample=0.9, colsample_bytree=0.9,
                        seed=0)  
xgb.fit(iris.data, iris.target)   
#y_pred = xgb.predict_proba(X_test)
score = cross_val_score(xgb,iris.data,iris.target)                       
print(score.mean()) 

0.9669117647058822


/home/vimal/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/vimal/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/vimal/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [11]:
import numpy as np
nx, ny = (5, 4)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
xv, yv = np.meshgrid(x, y)
print(x)
print(y)
print(xv)
print(yv)

[0.   0.25 0.5  0.75 1.  ]
[0.         0.33333333 0.66666667 1.        ]
[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]]
[[0.         0.         0.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]
 [0.66666667 0.66666667 0.66666667 0.66666667 0.66666667]
 [1.         1.         1.         1.         1.        ]]


In [3]:

X = np.random.randn(1, 2)
X_train = np.r_['-1',X,X+1]
print(X)
print(X_train)


[[ 0.95885015 -1.29063563]]
[[ 0.95885015 -1.29063563  1.95885015 -0.29063563]]


In [9]:
a = np.arange(10).reshape(2,5)
a.reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [16]:
X = 0.3 * np.random.randn(10, 2)
X_outliers = np.random.uniform(low=-4, high=4, size=(20, 2))
X_outliers

array([[ 0.19375437, -1.48892761],
       [-1.36568574, -2.65079589],
       [ 3.86067231,  3.36146339],
       [-2.41104146, -3.52570066],
       [ 3.50846611, -2.48369943],
       [-2.8486108 , -1.01003719],
       [ 0.09618668, -1.37215114],
       [ 2.73286438,  1.55381054],
       [-0.54667929,  0.95645933],
       [ 3.60825605,  2.94118931],
       [-3.23412863, -3.02058147],
       [ 0.80841515,  0.46790762],
       [ 1.26459396, -1.53119235],
       [ 1.23252299, -2.45888629],
       [ 1.60527431,  3.56139094],
       [ 1.95828139,  0.85857732],
       [ 1.2516786 ,  3.39602248],
       [ 2.63200606, -1.46052799],
       [ 0.87884268,  2.75352369],
       [-2.98551014,  0.05303036]])

In [25]:
s = [1,2,1,2,1,2,1,2,1,2,1,2,1,1]
t = np.array(s)
q = t[t==2].size
q

6