In [2]:
import pandas as pd
from sklearn.feature_selection import f_regression
from scipy.optimize import minimize
df = pd.read_csv('train.csv')
import numpy as np
#print(df[:][2:])
from sklearn import linear_model
from sklearn.preprocessing import PolynomialFeatures,StandardScaler
import matplotlib.pyplot as plt
lr = linear_model.LinearRegression(fit_intercept=True,normalize=True)
pl = PolynomialFeatures(degree=2)

m = max(df['weight'])
#df['weight'] = df['weight']/m

acc = np.array(df[['acceleation','cylinders','hp','weight','model','origin']])
#print(df[['acceleation','cylinders']])
mpg = np.array(df['mpg'])
#acc = StandardScaler.fit_transform(acc)
plnew = pl.fit_transform(acc[:300])
#pl = np.poly1d(np.polyfit(acc[:300],mpg[:300],3))
lr.fit(plnew,mpg[:300])
print(lr.score(pl.fit_transform(acc[300:]),mpg[300:]))

for i in zip(lr.predict(pl.fit_transform(acc[300:])),mpg[300:]):
    print(i)





0.10536217473134411
(37.375, 38.1)
(34.625, 32.1)
(35.75, 37.2)
(31.75, 28.0)
(30.5, 26.4)
(29.875, 24.3)
(23.875, 19.1)
(31.75, 34.3)
(28.625, 29.8)
(31.75, 31.3)
(28.75, 37.0)
(32.625, 32.2)
(35.625, 46.6)
(32.0, 27.9)
(35.75, 40.8)
(35.875, 44.3)
(34.375, 43.4)
(29.0, 36.4)
(26.375, 30.0)
(36.0, 44.6)
(34.875, 33.8)
(35.5, 29.8)
(21.75, 32.7)
(27.125, 23.7)
(29.5, 35.0)
(33.25, 32.4)
(34.75, 27.2)
(33.875, 26.6)
(34.375, 25.8)
(29.625, 23.5)
(35.375, 30.0)
(40.25, 39.1)
(38.875, 39.0)
(39.625, 35.1)
(36.875, 32.3)
(38.0, 37.0)
(38.125, 37.7)
(36.875, 34.1)
(36.125, 34.7)
(37.375, 34.4)
(35.5, 29.9)
(34.0, 33.0)
(34.625, 33.7)
(34.125, 32.4)
(28.75, 32.9)
(33.625, 31.6)
(28.625, 28.1)
(30.875, 30.7)
(27.75, 25.4)
(26.375, 24.2)
(26.875, 22.4)
(25.0, 26.6)
(28.375, 20.2)
(26.25, 17.6)
(37.75, 28.0)
(37.25, 27.0)
(38.5, 34.0)
(36.875, 31.0)
(37.125, 29.0)
(36.625, 27.0)
(35.625, 24.0)
(37.375, 36.0)
(39.125, 37.0)
(39.25, 31.0)
(39.375, 38.0)
(39.5, 36.0)
(33.5, 36.0)
(36.375, 36.0)
(3

In [10]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

X = np.arange(0,6).reshape(3,2)
print(X)
poly = PolynomialFeatures(2)
print(poly.fit_transform(X))

poly = PolynomialFeatures(interaction_only=True)
print(poly.fit_transform(X))


[[0 1]
 [2 3]
 [4 5]]
[[ 1.  0.  1.  0.  0.  1.]
 [ 1.  2.  3.  4.  6.  9.]
 [ 1.  4.  5. 16. 20. 25.]]
[[ 1.  0.  1.  0.]
 [ 1.  2.  3.  6.]
 [ 1.  4.  5. 20.]]


In [7]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.polyfit(x, y, 2)
print(z)
p = np.poly1d(z)
print(p)

[-9.18852826e-16  1.00000000e+00  3.00000000e+00]
            2
-9.189e-16 x + 1 x + 3


In [51]:
from scipy.optimize import minimize, rosen, rosen_der



x0 = [1,2]
def test(x0):
    return ((x0[0]-5)**2+(x0[1]-5)**2)
res = minimize(test,x0, method='BFGS', tol=1e-6)
res.x

array([5.00000008, 4.99999988])

In [8]:
from sklearn.preprocessing import PolynomialFeatures
pl = PolynomialFeatures(degree=2)

plnew = pl.fit_transform([[2, 3]])
plnew

array([[1., 2., 3., 4., 6., 9.]])