In [3]:
import numpy as np
from sklearn.decomposition import PCA
X = np.array([[-1, -1,3,4,5,6], [-2, -1,7,8,9,3], [-3, -2,1,2,3,4]])
pca = PCA(n_components=3)
x = pca.fit_transform(X)
print(x)

print(sum(pca.explained_variance_ratio_))  
print(pca.components_)
print(pca.singular_values_)  

[[-1.29783623e+00  1.88091556e+00  3.52703906e-16]
 [ 5.90521697e+00 -5.92144199e-01  3.52703906e-16]
 [-4.60738074e+00 -1.28877136e+00  3.52703906e-16]]
1.0
[[ 0.05727449  0.07973465  0.56824852  0.56824852  0.56824852 -0.14711513]
 [ 0.57117551  0.23223576  0.03765552  0.03765552  0.03765552  0.7845835 ]
 [-0.21841727 -0.61276584  0.61513662 -0.21071236 -0.21071236  0.33108829]]
[7.60157376e+00 2.35571851e+00 6.10901085e-16]


In [ ]:
import pandas as pd

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# load dataset into Pandas DataFrame
df = pd.read_csv(url, names=['sepal length','sepal width','petal length','petal width','target'])
from sklearn.preprocessing import StandardScaler

features = ['sepal length', 'sepal width', 'petal length', 'petal width']

# Separating out the features
x = df.loc[:, features].values

# Separating out the target
y = df.loc[:,['target']].values

# Standardizing the features
x = StandardScaler().fit_transform(x)
print(x[:5])
from sklearn.decomposition import PCA

pca = PCA(n_components=2)

principalComponents = pca.fit_transform(x)

principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2'])

print(principalDf.head())
print(pca.singular_values_,"hello",sum(pca.explained_variance_ratio_))

In [7]:
import numpy as np

x = np.arange(4096).reshape(64,64).reshape(4096,)
x

array([   0,    1,    2, ..., 4093, 4094, 4095])